# Generated by Django 5.1.4 on 2024-12-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Titre', models.CharField(max_length=245)),
                ('Auteur', models.CharField(max_length=245)),
                ('Domaine', models.CharField(max_length=245)),
                ('Date', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=345)),
                ('Image', models.ImageField(upload_to='livre_image/')),
            ],
        ),
    ]
