# Generated by Django 5.1.4 on 2024-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='pdf',
            field=models.FileField(default=0, upload_to='livre_pdf/'),
            preserve_default=False,
        ),
    ]
