# Generated by Django 5.1.4 on 2024-12-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0002_livre_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='Nb_lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livre',
            name='Note',
            field=models.FloatField(default=0),
        ),
    ]
