# Generated by Django 5.1.4 on 2024-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0003_livre_nb_lecture_livre_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='livre_image/'),
        ),
    ]
