# Generated by Django 5.1.4 on 2025-01-01 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0005_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
