# Generated by Django 5.1.4 on 2024-12-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='education_level',
            new_name='Nom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='Prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lecture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
